In [1]:
import numpy as np

# Creating arrays
arr1 = np.array([1, 2, 3, 4, 5])

print("Array:")
print(arr1)

# Mathematical operations
print("Multiply by 2:")
print(arr1 * 2)

print("Addition:")
print(arr1 + 10)

# Mean value
print("Mean:", np.mean(arr1))

# Maximum value
print("Max:", np.max(arr1))

Array:
[1 2 3 4 5]
Multiply by 2:
[ 2  4  6  8 10]
Addition:
[11 12 13 14 15]
Mean: 3.0
Max: 5
